name: Go Lint

on:
  push:
    branches:
      - 4.x
  pull_request:
    branches:
      - 4.x

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: stable
          check-latest: true
          cache-dependency-path: "**/go.sum"

      - name: Run linters
        run: make lint