name: Go Nilaway

on:
  push:
    branches:
      - 4.x
  pull_request:
    branches:
      - 4.x

jobs:
  nilaway:
    name: nilaway
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install nilaway
        run: go install go.uber.org/nilaway/cmd/nilaway@latest

      - name: nilaway
        run: ~/go/bin/nilaway ./...
        continue-on-error: true